#!/usr/bin/env node
'use strict';

// Developer-only asset generation; Sharp is not an application dependency.
// Use sharp@0.35.4 to reproduce the checked-in PNGs from static/keep-icon.svg.
// Run with --check to verify generated bytes without modifying any assets.
const fs = require('node:fs/promises');
const path = require('node:path');
let sharp;
try {
  sharp = require('sharp');
} catch {
  throw new Error('Icon generation requires the developer dependency sharp@0.35.4.');
}
if (sharp.versions.sharp !== '0.35.4') {
  throw new Error('Use sharp@0.35.4 for deterministic icon generation.');
}

const staticDirectory = path.resolve(__dirname, '..', 'static');
const brandingDirectory = path.resolve(__dirname, '..', 'docs', 'branding');
const outputs = [
  ['favicon-32.png', 32],
  ['apple-touch-icon.png', 180],
  ['keep-icon-192.png', 192],
  ['keep-icon-512.png', 512],
];

async function main() {
  const options = process.argv.slice(2);
  if (options.some(option => option !== '--check') || options.length > 1) {
    throw new Error('Usage: node scripts/generate_brand_icons.cjs [--check]');
  }
  const check = options.includes('--check');
  const svg = await fs.readFile(path.join(staticDirectory, 'keep-icon.svg'));
  if (!/viewBox="0 0 96 96"/.test(svg.toString('utf8'))) {
    throw new Error('Expected the approved 96×96 canonical Keep icon.');
  }
  for (const [name, size] of outputs) {
    // Rasterize the SVG at each final resolution, without theme substitutions.
    const buffer = await sharp(svg, { density: 72 * size / 96 })
      .resize(size, size, { fit: 'fill' })
      .png({ compressionLevel: 9, adaptiveFiltering: false, palette: false })
      .toBuffer();
    const file = path.join(staticDirectory, name);
    if (check) {
      if (!buffer.equals(await fs.readFile(file))) {
        throw new Error('Regenerated icon differs: ' + name);
      }
    } else {
      await fs.writeFile(file, buffer);
    }
    process.stdout.write(`${check ? 'Verified' : 'Generated'} ${name}: ${size}×${size}\n`);
  }
  const embeddedLogo = 'data:image/svg+xml;base64,' + svg.toString('base64');
  for (const [name, width, height] of [
    ['social-preview', 1280, 640],
    ['repository-banner', 1280, 400],
  ]) {
    const source = path.join(brandingDirectory, name + '.svg');
    const originalSvg = await fs.readFile(source, 'utf8');
    const composition = originalSvg.replace(
      /(<image id="keep-logo" href=")[^"]*(")/,
      (_, before, after) => before + embeddedLogo + after,
    );
    if (composition === originalSvg && !originalSvg.includes(embeddedLogo)) {
      throw new Error(name + ' must contain the canonical Keep logo image.');
    }
    const buffer = await sharp(Buffer.from(composition))
      .resize(width, height, { fit: 'fill' })
      .png({ compressionLevel: 9, adaptiveFiltering: false, palette: false })
      .toBuffer();
    const output = path.join(brandingDirectory, name + '.png');
    if (check) {
      if (composition !== originalSvg || !buffer.equals(await fs.readFile(output))) {
        throw new Error('Regenerated ' + name + ' differs.');
      }
    } else {
      await fs.writeFile(source, composition);
      await fs.writeFile(output, buffer);
    }
    process.stdout.write(`${check ? 'Verified' : 'Generated'} ${name}.png: ${width}×${height}\n`);
  }
}

main().catch(error => {
  process.stderr.write(error.message + '\n');
  process.exitCode = 1;
});
